development:
  adapter: mysql2
  database: dev_reffy
  host: 127.0.0.1
  enconding: utf8
  pool: 8
  timeout: 5000
  user: root
  password: mysql

test:
  adapter: mysql2
  database: test_reffy
  host: 127.0.0.1
  enconding: utf8
  pool: 8
  timeout: 5000
  user: root
  password: mysql

production:
  adapter: postgresql
  database: prod_reffy
  enconding: utf8
  pool: 5
  timeout: 5000
