# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Sport.create(name: 'Sport 1')
Sport.create(name: 'Sport 2')
Sport.create(name: 'Sport 2')
Sport.create(name: 'Sport 4')
Sport.create(name: 'Sport 5')
Sport.create(name: 'Sport 6')
Sport.create(name: 'Sport 7')

User.create(name:'Jhon Doe 1',city:'Bucuresti',fb_id:'jhon-doe1')
User.create(name:'Jhon Doe 2',city:'Bucuresti',fb_id:'jhon-doe2')
User.create(name:'Jhon Doe 3',city:'Iasi',fb_id:'jhon-doe3')
User.create(name:'Jhon Doe 4',city:'Ploiesti',fb_id:'jhon-doe4')
User.create(name:'Jhon Doe 5',city:'Pitesti',fb_id:'jhon-doe5')
User.create(name:'Jhon Doe 6',city:'Ploiesti',fb_id:'jhon-doe6')
User.create(name:'Jhon Doe 7',city:'Constanta',fb_id:'jhon-doe7')
User.create(name:'Jhon Doe 8',city:'Timisoara',fb_id:'jhon-doe8')
User.create(name:'Jhon Doe 9',city:'Galati',fb_id:'jhon-doe9')
User.create(name:'Jhon Doe 10',city:'Braila',fb_id:'jhon-doe10')
User.create(name:'Jhon Doe 11',city:'Brasov',fb_id:'jhon-doe29')
User.create(name:'Jhon Doe 12',city:'Sibiu',fb_id:'jhon-doe30')
User.create(name:'Jhon Doe 13',city:'Bucuresti',fb_id:'jhon-doe13')
User.create(name:'Jhon Doe 14',city:'Bucuresti',fb_id:'jhon-doe14')
User.create(name:'Jhon Doe 15',city:'Bucuresti',fb_id:'jhon-doe15')
User.create(name:'Jhon Doe 16',city:'Bucuresti',fb_id:'jhon-doe16')
User.create(name:'Jhon Doe 17',city:'Bucuresti',fb_id:'jhon-doe17')
User.create(name:'Jhon Doe 18',city:'Bucuresti',fb_id:'jhon-doe18')
User.create(name:'Jhon Doe 19',city:'Bucuresti',fb_id:'jhon-doe19')
User.create(name:'Jhon Doe 20',city:'Bucuresti',fb_id:'jhon-doe20')
User.create(name:'Jhon Doe 21',city:'Bucuresti',fb_id:'jhon-doe21')
User.create(name:'Jhon Doe 22',city:'Bucuresti',fb_id:'jhon-doe22')
User.create(name:'Jhon Doe 23',city:'Bucuresti',fb_id:'jhon-doe23')
User.create(name:'Jhon Doe 24',city:'Bucuresti',fb_id:'jhon-doe24')
User.create(name:'Jhon Doe 25',city:'Bucuresti',fb_id:'jhon-doe25')
User.create(name:'Jhon Doe 26',city:'Bucuresti',fb_id:'jhon-doe26')
User.create(name:'Jhon Doe 27',city:'Bucuresti',fb_id:'jhon-doe27')
User.create(name:'Jhon Doe 28',city:'Bucuresti',fb_id:'jhon-doe28')
User.create(name:'Jhon Doe 29',city:'Bucuresti',fb_id:'jhon-doe29')
User.create(name:'Jhon Doe 30',city:'Bucuresti',fb_id:'jhon-doe30')
User.create(name:'Jhon Doe 31',city:'Bucuresti',fb_id:'jhon-doe31')
User.create(name:'Jhon Doe 32',city:'Bucuresti',fb_id:'jhon-doe32')
User.create(name:'Jhon Doe 33',city:'Bucuresti',fb_id:'jhon-doe33')
User.create(name:'Jhon Doe 34',city:'Bucuresti',fb_id:'jhon-doe34')
User.create(name:'Jhon Doe 35',city:'Bucuresti',fb_id:'jhon-doe35')
User.create(name:'Jhon Doe 36',city:'Bucuresti',fb_id:'jhon-doe36')
User.create(name:'Jhon Doe 37',city:'Bucuresti',fb_id:'jhon-doe37')
User.create(name:'Jhon Doe 38',city:'Bucuresti',fb_id:'jhon-doe38')
User.create(name:'Jhon Doe 39',city:'Bucuresti',fb_id:'jhon-doe39')
User.create(name:'Jhon Doe 40',city:'Bucuresti',fb_id:'jhon-doe40')
User.create(name:'Jhon Doe 41',city:'Bucuresti',fb_id:'jhon-doe41')
User.create(name:'Jhon Doe 42',city:'Bucuresti',fb_id:'jhon-doe42')
User.create(name:'Jhon Doe 43',city:'Bucuresti',fb_id:'jhon-doe43')
User.create(name:'Jhon Doe 44',city:'Bucuresti',fb_id:'jhon-doe44')
User.create(name:'Jhon Doe 45',city:'Bucuresti',fb_id:'jhon-doe45')
User.create(name:'Jhon Doe 46',city:'Bucuresti',fb_id:'jhon-doe46')
User.create(name:'Jhon Doe 47',city:'Bucuresti',fb_id:'jhon-doe47')
User.create(name:'Jhon Doe 48',city:'Bucuresti',fb_id:'jhon-doe48')
User.create(name:'Jhon Doe 49',city:'Bucuresti',fb_id:'jhon-doe49')
User.create(name:'Jhon Doe 50',city:'Bucuresti',fb_id:'jhon-doe50')
User.create(name:'Jhon Doe 51',city:'Bucuresti',fb_id:'jhon-doe51')
User.create(name:'Jhon Doe 52',city:'Bucuresti',fb_id:'jhon-doe52')
User.create(name:'Jhon Doe 53',city:'Bucuresti',fb_id:'jhon-doe53')
User.create(name:'Jhon Doe 54',city:'Bucuresti',fb_id:'jhon-doe54')
User.create(name:'Jhon Doe 55',city:'Bucuresti',fb_id:'jhon-doe55')
User.create(name: 'Jhon Doe 56', city: 'Bucuresti', fb_id: 'jhon-doe56')

Tournament.create(name:'Football Masters',data: DateTime.new(2012,11,20),sport_id:1)
Tournament.create(name:'Play Day',data:DateTime.new(2012,11,30),sport_id:3)
Tournament.create(name:'The CUP',data: DateTime.new(2012,11,29),sport_id:2)
Tournament.create(name:'Play & Win',data:DateTime.new(2012,12,7),sport_id:4)
Tournament.create(name:'The Football Stars',data:DateTime.new(2012,11,13),sport_id:1)
Tournament.create(name:'Winner`s Race',data:DateTime.new(2012,1,9),sport_id:5)
Tournament.create(name:'Milky Way Stars',data:DateTime.new(2012,9,8),sport_id:6)
Tournament.create(name:'Nike Cup',data:DateTime.new(2012,12,20),sport_id:7)

Team.create(name:'Team1',captain_id:1)
Team.create(name:'Team2',captain_id:2)
Team.create(name:'Team3',captain_id:3)
Team.create(name:'Team4',captain_id:4)
Team.create(name:'Team5',captain_id:5)
Team.create(name:'Team6',captain_id:6)
Team.create(name:'Team7',captain_id:7)
Team.create(name:'Team8',captain_id:8)
Team.create(name:'Team9',captain_id:9)
Team.create(name:'Team10',captain_id:10)
Team.create(name:'Team11',captain_id:11)

Team.create(name:'Team12',captain_id:12)


Game.create(latitude:"44.437711",longitude:"26.097367",scor_team1:1,scor_team2:0,duration:45,team1_name:'1',team2_name:'2',state:"on",sport_id:1)
Game.create(latitude:"44.431711",longitude:"26.087367",scor_team1:3,scor_team2:2,duration:90,team1_name:'3',team2_name:'4',state:"on",sport_id:1)
Game.create(latitude:"44.435311",longitude:"26.097367",scor_team1:2,scor_team2:2,duration:92,team1_name:'5',team2_name:'6',state:"off",sport_id:1)
Game.create(latitude:"44.432001",longitude:"26.086367",scor_team1:1,scor_team2:2,duration:76,team1_name:'7',team2_name:'8',state:"on",sport_id:1)
Game.create(latitude:"44.432311",longitude:"26.084367",scor_team1:0,scor_team2:3,duration:91,team1_name:'9',team2_name:'10',state:"off",sport_id:1)
Game.create(latitude:"44.435011",longitude:"26.107367",scor_team1:8,scor_team2:10,duration:20,team1_name:'17',team2_name:'18',state:"on",sport_id:6)
Game.create(latitude:"44.433511",longitude:"26.086267",scor_team1:12,scor_team2:18,duration:55,team1_name:'19',team2_name:'20',state:"on",sport_id:6)
Game.create(latitude:"44.435511",longitude:"26.102328",scor_team1:35,scor_team2:45,duration:45,team1_name:'21',team2_name:'22',state:"on",sport_id:7)
Game.create(latitude:"44.434511",longitude:"26.102228",scor_team1:20,scor_team2:23,duration:30,team1_name:'15',team2_name:'16',state:"on",sport_id:5)
Game.create(latitude:"44.435211",longitude:"26.102528",scor_team1:2,scor_team2:2,duration:78,team1_name:'25',team2_name:'26',state:"on",sport_id:1)


Game.create(latitude:"44.437711",longitude:"26.097367",scor_team1:1,scor_team2:0,duration:45,team1_name:"team1",team2_name:"team2",state:"on",sport_id:1)
Game.create(latitude:"44.431711",longitude:"26.087367",scor_team1:3,scor_team2:2,duration:90,team1_name:"team3",team2_name:"team1",state:"on",sport_id:1)

Tournament_game.create(tournament_id:1,game_id:1)
Tournament_game.create(tournament_id:1,game_id:2)
Tournament_game.create(tournament_id:1,game_id:3)
Tournament_game.create(tournament_id:1,game_id:4)

