# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Sport.create (name: 'Sport 1', type:'Football')
Sport.create (name: 'Sport 2', type:'Tennis')
Sport.create (name: 'Sport 3', type:'Ping-Pong')
Sport.create (name: 'Sport 4', type:'Backgammon')
Sport.create (name: 'Sport 5', type:'Volleyball')
Sport.create (name: 'Sport 6', type:'Handball')
Sport.create (name: 'Sport 7', type:'Basketball')

User.create(name:'Jhon Doe 1',initial:'A',email:'jhonny1@example.com',city:'Bucuresti',fb_id:'jhon-doe1')
User.create(name:'Jhon Doe 2',initial:'B',email:'jhonny2@example.com',city:'Bucuresti',fb_id:'jhon-doe2')
User.create(name:'Jhon Doe 3',initial:'C',email:'jhonny3@example.com',city:'Iasi',fb_id:'jhon-doe3')
User.create(name:'Jhon Doe 4',initial:'D',email:'jhonny4@example.com',city:'Ploiesti',fb_id:'jhon-doe4')
User.create(name:'Jhon Doe 5',initial:'E',email:'jhonny5@example.com',city:'Pitesti',fb_id:'jhon-doe5')
User.create(name:'Jhon Doe 6',initial:'F',email:'jhonny6@example.com',city:'Ploiesti',fb_id:'jhon-doe6')
User.create(name:'Jhon Doe 7',initial:'G',email:'jhonny7@example.com',city:'Constanta',fb_id:'jhon-doe7')
User.create(name:'Jhon Doe 8',initial:'H',email:'jhonny8@example.com',city:'Timisoara',fb_id:'jhon-doe8')
User.create(name:'Jhon Doe 9',initial:'I',email:'jhonny9@example.com',city:'Galati',fb_id:'jhon-doe9')
User.create(name:'Jhon Doe 10',initial:'J',email:'jhonny10@example.com',city:'Braila',fb_id:'jhon-doe10')
User.create(name:'Jhon Doe 11',initial:'K',email:'jhonny11@example.com',city:'Vama Veche',fb_id:'jhon-doe11')
User.create(name:'Jhon Doe 12',initial:'L',email:'jhonny12@example.com',city:'Slobozia',fb_id:'jhon-doe12')
User.create(name:'Jhon Doe 13',initial:'M',email:'jhonny13@example.com',city:'Bacau',fb_id:'jhon-doe13')
User.create(name:'Jhon Doe 14',initial:'N',email:'jhonny14@example.com',city:'Bacau',fb_id:'jhon-doe14')
User.create(name:'Jhon Doe 15',initial:'O',email:'jhonny15@example.com',city:'Bacau',fb_id:'jhon-doe15')
User.create(name:'Jhon Doe 16',initial:'P',email:'jhonny16@example.com',city:'Bacau',fb_id:'jhon-doe16')
User.create(name:'Jhon Doe 17',initial:'Q',email:'jhonny17@example.com',city:'Bacau',fb_id:'jhon-doe17')
User.create(name:'Jhon Doe 18',initial:'R',email:'jhonny18@example.com',city:'Bucuresti',fb_id:'jhon-doe18')
User.create(name:'Jhon Doe 19',initial:'S',email:'jhonny19@example.com',city:'Bucuresti',fb_id:'jhon-doe19')
User.create(name:'Jhon Doe 20',initial:'T',email:'jhonny20@example.com',city:'Bucuresti',fb_id:'jhon-doe20')
User.create(name:'Jhon Doe 21',initial:'U',email:'jhonny21@example.com',city:'Bucuresti',fb_id:'jhon-doe21')
User.create(name:'Jhon Doe 22',initial:'V',email:'jhonny22@example.com',city:'Arad',fb_id:'jhon-doe22')
User.create(name:'Jhon Doe 23',initial:'X',email:'jhonny23@example.com',city:'Bucuresti',fb_id:'jhon-doe23')
User.create(name:'Jhon Doe 24',initial:'Z',email:'jhonny24@example.com',city:'Bucuresti',fb_id:'jhon-doe24')
User.create(name:'Jhon Doe 25',initial:'A',email:'jhonny25@example.com',city:'Roman',fb_id:'jhon-doe25')
User.create(name:'Jhon Doe 26',initial:'B',email:'jhonny26@example.com',city:'Iasi',fb_id:'jhon-doe26')
User.create(name:'Jhon Doe 27',initial:'C',email:'jhonny27@example.com',city:'Sibiu',fb_id:'jhon-doe27')
User.create(name:'Jhon Doe 28',initial:'D',email:'jhonny28@example.com',city:'Sibiu',fb_id:'jhon-doe28')
User.create(name:'Jhon Doe 29',initial:'E',email:'jhonny29@example.com',city:'Brasov',fb_id:'jhon-doe29')
User.create(name:'Jhon Doe 30',initial:'F',email:'jhonny30@example.com',city:'Sibiu',fb_id:'jhon-doe30')
User.create(name:'Jhon Doe 31',initial:'G',email:'jhonny31@example.com',city:'Baia-Mare',fb_id:'jhon-doe31')
User.create(name:'Jhon Doe 32',initial:'H',email:'jhonny32@example.com',city:'Baia-Mare',fb_id:'jhon-doe32')
User.create(name:'Jhon Doe 33',initial:'I',email:'jhonny33@example.com',city:'Bistrita',fb_id:'jhon-doe33')
User.create(name:'Jhon Doe 34',initial:'J',email:'jhonny34@example.com',city:'Tulcea',fb_id:'jhon-doe34')
User.create(name:'Jhon Doe 35',initial:'K',email:'jhonny35@example.com',city:'Tulcea',fb_id:'jhon-doe35')
User.create(name:'Jhon Doe 36',initial:'L',email:'jhonny36@example.com',city:'Tecuci',fb_id:'jhon-doe36')
User.create(name:'Jhon Doe 37',initial:'M',email:'jhonny37@example.com',city:'Barlad',fb_id:'jhon-doe37')
User.create(name:'Jhon Doe 38',initial:'N',email:'jhonny38@example.com',city:'Focsani',fb_id:'jhon-doe38')
User.create(name:'Jhon Doe 39',initial:'O',email:'jhonny39@example.com',city:'Bucuresti',fb_id:'jhon-doe39')
User.create(name:'Jhon Doe 40',initial:'P',email:'jhonny40@example.com',city:'Bucuresti',fb_id:'jhon-doe40')
User.create(name:'Jhon Doe 41',initial:'Q',email:'jhonny41@example.com',city:'Bucuresti',fb_id:'jhon-doe41')
User.create(name:'Jhon Doe 42',initial:'R',email:'jhonny42@example.com',city:'Bucuresti',fb_id:'jhon-doe42')
User.create(name:'Jhon Doe 43',initial:'S',email:'jhonny43@example.com',city:'Iasi',fb_id:'jhon-doe43')
User.create(name:'Jhon Doe 44',initial:'T',email:'jhonny44@example.com',city:'Psacani',fb_id:'jhon-doe44')
User.create(name:'Jhon Doe 45',initial:'U',email:'jhonny45@example.com',city:'Zimnicea',fb_id:'jhon-doe45')
User.create(name:'Jhon Doe 46',initial:'V',email:'jhonny46@example.com',city:'Oradea',fb_id:'jhon-doe46')
User.create(name:'Jhon Doe 47',initial:'X',email:'jhonny47@example.com',city:'Cluj-Napoca',fb_id:'jhon-doe47')
User.create(name:'Jhon Doe 48',initial:'Z',email:'jhonny48@example.com',city:'Bucuresti',fb_id:'jhon-doe48')
User.create(name:'Jhon Doe 49',initial:'A',email:'jhonny49@example.com',city:'Bucuresti',fb_id:'jhon-doe49')
User.create(name:'Jhon Doe 50',initial:'A',email:'jhonny50@example.com',city:'Bucuresti',fb_id:'jhon-doe50')
User.create(name:'Jhon Doe 51',initial:'B',email:'jhonny51@example.com',city:'Bucuresti',fb_id:'jhon-doe51')
User.create(name:'Jhon Doe 52',initial:'C',email:'jhonny52@example.com',city:'Bucuresti',fb_id:'jhon-doe52')
User.create(name:'Jhon Doe 53',initial:'D',email:'jhonny53@example.com',city:'Bucuresti',fb_id:'jhon-doe53')
User.create(name:'Jhon Doe 54',initial:'E',email:'jhonny54@example.com',city:'Bucuresti',fb_id:'jhon-doe54')
User.create(name:'Jhon Doe 55',initial:'F',email:'jhonny55@example.com',city:'Bucuresti',fb_id:'jhon-doe55')
User.create(name:'Jhon Doe 56',initial:'G',email:'jhonny56@example.com',city:'Bucuresti',fb_id:'jhon-doe56')
User.create(name:'Jhon Doe 57',initial:'H',email:'jhonny57@example.com',city:'Bucuresti',fb_id:'jhon-doe57')
User.create(name:'Jhon Doe 58',initial:'J',email:'jhonny58@example.com',city:'Bucuresti',fb_id:'jhon-doe58')
User.create(name:'Jhon Doe 59',initial:'K',email:'jhonny59@example.com',city:'Bucuresti',fb_id:'jhon-doe59')
User.create(name:'Jhon Doe 60',initial:'L',email:'jhonny60@example.com',city:'Bucuresti',fb_id:'jhon-doe60')

Tournament.create(name:'Football Masters',data: DateTime.new(2012,11,20),sport_id:1)
Tournament.create(name:'Play Day',data:DateTime.new(2012,11,30),sport_id:3)
Tournament.create(name:'The CUP',data: DateTime.new(2012,11,31),sport_id:2)
Tournament.create(name:'Play & Win',data:DateTime.new(2012,12,7),sport_id:4)
Tournament.create(name:'The Football Stars',data:DateTime.new(2012,11,13),sport_id:1)
Tournament.create(name:'Winner`s Race',data:DateTime.new(2012,1,9),sport_id:5)
Tournament.create(name:'Milky Way Stars',data:DateTime.new(2012,9,8),sport_id:6)
Tournament.create(name:'Nike Cup',data:DateTime.new(2012,12,20),sport_id:7)

Team.create(name:'Team1',captain_id:1,sport_id:1)
Team.create(name:'Team2',captain_id:2,sport_id:1)
Team.create(name:'Team3',captain_id:3,sport_id:1)
Team.create(name:'Team4',captain_id:4,sport_id:1)
Team.create(name:'Team5',captain_id:5,sport_id:1)
Team.create(name:'Team6',captain_id:6,sport_id:1)
Team.create(name:'Team7',captain_id:7,sport_id:1)
Team.create(name:'Team8',captain_id:8,sport_id:1)
Team.create(name:'Team9',captain_id:9,sport_id:1)
Team.create(name:'Team10',captain_id:10,sport_id:1)
Team.create(name:'Team11',captain_id:11,sport_id:3)
Team.create(name:'Team12',captain_id:35,sport_id:3)
Team.create(name:'Team13',captain_id:37,sport_id:4)
Team.create(name:'Team14',captain_id:38,sport_id:4)
Team.create(name:'Team15',captain_id:39,sport_id:5)
Team.create(name:'Team16',captain_id:40,sport_id:5)
Team.create(name:'Team17',captain_id:41,sport_id:6)
Team.create(name:'Team18',captain_id:42,sport_id:6)
Team.create(name:'Team19',captain_id:43,sport_id:6)
Team.create(name:'Team20',captain_id:44,sport_id:6)
Team.create(name:'Team21',captain_id:45,sport_id:7)
Team.create(name:'Team22',captain_id:46,sport_id:7)
Team.create(name:'Team23',captain_id:47,sport_id:1)
Team.create(name:'Team24',captain_id:48,sport_id:1)
Team.create(name:'Team25',captain_id:49,sport_id:1)
Team.create(name:'Team26',captain_id:50,sport_id:1)

Game.create(latitude:"44.437711",longitude:"26.097367",scor_team1:1,scor_team2:0,duration:45,team1_id:1,team2_id:2,state:"on")
Game.create(latitude:"44.431711",longitude:"26.087367",scor_team1:3,scor_team2:2,duration:90,team1_id:3,team2_id:4,state:"on")
Game.create(latitude:"44.435311",longitude:"26.097367",scor_team1:2,scor_team2:2,duration:92,team1_id:5,team2_id:6,state:"off")
Game.create(latitude:"44.432001",longitude:"26.086367",scor_team1:1,scor_team2:2,duration:76,team1_id:7,team2_id:8,state:"on")
Game.create(latitude:"44.432311",longitude:"26.084367",scor_team1:0,scor_team2:3,duration:91,team1_id:9,team2_id:10,state:"off")
Game.create(latitude:"44.435011",longitude:"26.107367",scor_team1:8,scor_team2:10,duration:20,team1_id:17,team2_id:18,state:"on")
Game.create(latitude:"44.433511",longitude:"26.086267",scor_team1:12,scor_team2:18,duration:55,team1_id:19,team2_id:20,state:"on")
Game.create(latitude:"44.435511",longitude:"26.102328",scor_team1:35,scor_team2:45,duration:45,team1_id:21,team2_id:22,state:"on")
Game.create(latitude:"44.434511",longitude:"26.102228",scor_team1:20,scor_team2:23,duration:30,team1_id:15,team2_id:16,state:"on")
Game.create(latitude:"44.435211",longitude:"26.102528",scor_team1:2,scor_team2:2,duration:78,team1_id:25,team2_id:26,state:"on")

Team_game.create(team_id:1,game_id:1)
Team_game.create(team_id:2,game_id:1)
Team_game.create(team_id:3,game_id:2)
Team_game.create(team_id:4,game_id:2)
Team_game.create(team_id:5,game_id:3)
Team_game.create(team_id:6,game_id:3)
Team_game.create(team_id:7,game_id:4)
Team_game.create(team_id:8,game_id:4)
Team_game.create(team_id:9,game_id:5)
Team_game.create(team_id:10,game_id:5)
Team_game.create(team_id:17,game_id:6)
Team_game.create(team_id:18,game_id:6)
Team_game.create(team_id:19,game_id:7)
Team_game.create(team_id:20,game_id:7)
Team_game.create(team_id:21,game_id:8)
Team_game.create(team_id:22,game_id:8)
Team_game.create(team_id:15,game_id:9)
Team_game.create(team_id:16,game_id:9)
Team_game.create(team_id:25,game_id:10)
Team_game.create(team_id:26,game_id:10)

Team_player.create(team_id:1,user_id:1)
Team_player.create(team_id:1,user_id:12)
Team_player.create(team_id:1,user_id:13)
Team_player.create(team_id:1,user_id:14)
Team_player.create(team_id:2,user_id:15)
Team_player.create(team_id:2,user_id:2)
Team_player.create(team_id:2,user_id:16)
Team_player.create(team_id:2,user_id:17)
Team_player.create(team_id:3,user_id:18)
Team_player.create(team_id:3,user_id:19)
Team_player.create(team_id:3,user_id:3)
Team_player.create(team_id:3,user_id:20)
Team_player.create(team_id:4,user_id:21)
Team_player.create(team_id:4,user_id:22)
Team_player.create(team_id:4,user_id:23)
Team_player.create(team_id:4,user_id:4)
Team_player.create(team_id:5,user_id:24)
Team_player.create(team_id:5,user_id:5)
Team_player.create(team_id:5,user_id:25)
Team_player.create(team_id:6,user_id:6)
Team_player.create(team_id:6,user_id:26)
Team_player.create(team_id:7,user_id:27)
Team_player.create(team_id:7,user_id:7)
Team_player.create(team_id:8,user_id:8)
Team_player.create(team_id:8,user_id:28)
Team_player.create(team_id:9,user_id:9)
Team_player.create(team_id:9,user_id:29)
Team_player.create(team_id:10,user_id:10)
Team_player.create(team_id:10,user_id:30)
Team_player.create(team_id:15,user_id:31)
Team_player.create(team_id:15,user_id:39)
Team_player.create(team_id:16,user_id:32)
Team_player.create(team_id:16,user_id:40)
Team_player.create(team_id:17,user_id:33)
Team_player.create(team_id:17,user_id:41)
Team_player.create(team_id:18,user_id:34)
Team_player.create(team_id:18,user_id:42)
Team_player.create(team_id:19,user_id:51)
Team_player.create(team_id:19,user_id:43)
Team_player.create(team_id:20,user_id:52)
Team_player.create(team_id:20,user_id:44)
Team_player.create(team_id:21,user_id:53)
Team_player.create(team_id:21,user_id:45)
Team_player.create(team_id:22,user_id:54)
Team_player.create(team_id:22,user_id:46)
Team_player.create(team_id:25,user_id:55)
Team_player.create(team_id:25,user_id:49)
Team_player.create(team_id:26,user_id:56)
Team_player.create(team_id:26,user_id:50)

Tournament_game.create(tournament_id:1,game_id:1)
Tournament_game.create(tournament_id:1,game_id:2)
Tournament_game.create(tournament_id:1,game_id:3)
Tournament_game.create(tournament_id:1,game_id:4)

