# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Sport.create(name: 'Sport 1')
Sport.create(name: 'Sport 2')
Sport.create(name: 'Sport 2')
Sport.create(name: 'Sport 4')
Sport.create(name: 'Sport 5')
Sport.create(name: 'Sport 6')
Sport.create(name: 'Sport 7')

User.create(name:'Jhon Doe 1',city:'Bucuresti',fb_id:'jhon-doe1',email: 'jhon-doe1')
User.create(name:'Jhon Doe 2',city:'Bucuresti',fb_id:'jhon-doe2',email: :fb_id)
User.create(name:'Jhon Doe 3',city:'Iasi',fb_id:'jhon-doe3',email: :fb_id)
User.create(name:'Jhon Doe 4',city:'Ploiesti',fb_id:'jhon-doe4',email: :fb_id)
User.create(name:'Jhon Doe 5',city:'Pitesti',fb_id:'jhon-doe5',email: :fb_id)
User.create(name:'Jhon Doe 6',city:'Ploiesti',fb_id:'jhon-doe6',email: :fb_id)
User.create(name:'Jhon Doe 7',city:'Constanta',fb_id:'jhon-doe7',email: :fb_id)
User.create(name:'Jhon Doe 8',city:'Timisoara',fb_id:'jhon-doe8',email: :fb_id)
User.create(name:'Jhon Doe 9',city:'Galati',fb_id:'jhon-doe9',email: :fb_id)
User.create(name:'Jhon Doe 10',city:'Braila',fb_id:'jhon-doe10',email: :fb_id)
User.create(name:'Jhon Doe 11',city:'Brasov',fb_id:'jhon-doe29',email: :fb_id)
User.create(name:'Jhon Doe 12',city:'Sibiu',fb_id:'jhon-doe30',email: :fb_id)
User.create(name:'Jhon Doe 13',city:'Bucuresti',fb_id:'jhon-doe13',email: :fb_id)
User.create(name:'Jhon Doe 14',city:'Bucuresti',fb_id:'jhon-doe14',email: :fb_id)
User.create(name:'Jhon Doe 15',city:'Bucuresti',fb_id:'jhon-doe15',email: :fb_id)
User.create(name:'Jhon Doe 16',city:'Bucuresti',fb_id:'jhon-doe16',email: :fb_id)
User.create(name:'Jhon Doe 17',city:'Bucuresti',fb_id:'jhon-doe17',email: :fb_id)
User.create(name:'Jhon Doe 18',city:'Bucuresti',fb_id:'jhon-doe18',email: :fb_id)
User.create(name:'Jhon Doe 19',city:'Bucuresti',fb_id:'jhon-doe19',email: :fb_id)
User.create(name:'Jhon Doe 20',city:'Bucuresti',fb_id:'jhon-doe20',email: :fb_id)
User.create(name:'Jhon Doe 21',city:'Bucuresti',fb_id:'jhon-doe21',email: :fb_id)
User.create(name:'Jhon Doe 22',city:'Bucuresti',fb_id:'jhon-doe22',email: :fb_id)
User.create(name:'Jhon Doe 23',city:'Bucuresti',fb_id:'jhon-doe23',email: :fb_id)
User.create(name:'Jhon Doe 24',city:'Bucuresti',fb_id:'jhon-doe24',email: :fb_id)
User.create(name:'Jhon Doe 25',city:'Bucuresti',fb_id:'jhon-doe25',email: :fb_id)
User.create(name:'Jhon Doe 26',city:'Bucuresti',fb_id:'jhon-doe26',email: :fb_id)
User.create(name:'Jhon Doe 27',city:'Bucuresti',fb_id:'jhon-doe27',email: :fb_id)
User.create(name:'Jhon Doe 28',city:'Bucuresti',fb_id:'jhon-doe28',email: :fb_id)
User.create(name:'Jhon Doe 29',city:'Bucuresti',fb_id:'jhon-doe29',email: :fb_id)
User.create(name:'Jhon Doe 30',city:'Bucuresti',fb_id:'jhon-doe30',email: :fb_id)
User.create(name:'Jhon Doe 31',city:'Bucuresti',fb_id:'jhon-doe31',email: :fb_id)
User.create(name:'Jhon Doe 32',city:'Bucuresti',fb_id:'jhon-doe32',email: :fb_id)
User.create(name:'Jhon Doe 33',city:'Bucuresti',fb_id:'jhon-doe33',email: :fb_id)
User.create(name:'Jhon Doe 34',city:'Bucuresti',fb_id:'jhon-doe34',email: :fb_id)
User.create(name:'Jhon Doe 35',city:'Bucuresti',fb_id:'jhon-doe35',email: :fb_id)
User.create(name:'Jhon Doe 36',city:'Bucuresti',fb_id:'jhon-doe36',email: :fb_id)
User.create(name:'Jhon Doe 37',city:'Bucuresti',fb_id:'jhon-doe37',email: :fb_id)
User.create(name:'Jhon Doe 38',city:'Bucuresti',fb_id:'jhon-doe38',email: :fb_id)
User.create(name:'Jhon Doe 39',city:'Bucuresti',fb_id:'jhon-doe39',email: :fb_id)
User.create(name:'Jhon Doe 40',city:'Bucuresti',fb_id:'jhon-doe40',email: :fb_id)
User.create(name:'Jhon Doe 41',city:'Bucuresti',fb_id:'jhon-doe41',email: :fb_id)
User.create(name:'Jhon Doe 42',city:'Bucuresti',fb_id:'jhon-doe42',email: :fb_id)
User.create(name:'Jhon Doe 43',city:'Bucuresti',fb_id:'jhon-doe43',email: :fb_id)
User.create(name:'Jhon Doe 44',city:'Bucuresti',fb_id:'jhon-doe44',email: :fb_id)
User.create(name:'Jhon Doe 45',city:'Bucuresti',fb_id:'jhon-doe45',email: :fb_id)
User.create(name:'Jhon Doe 46',city:'Bucuresti',fb_id:'jhon-doe46',email: :fb_id)
User.create(name:'Jhon Doe 47',city:'Bucuresti',fb_id:'jhon-doe47',email: :fb_id)
User.create(name:'Jhon Doe 48',city:'Bucuresti',fb_id:'jhon-doe48',email: :fb_id)
User.create(name:'Jhon Doe 49',city:'Bucuresti',fb_id:'jhon-doe49',email: :fb_id)
User.create(name:'Jhon Doe 50',city:'Bucuresti',fb_id:'jhon-doe50',email: :fb_id)
User.create(name:'Jhon Doe 51',city:'Bucuresti',fb_id:'jhon-doe51',email: :fb_id)
User.create(name:'Jhon Doe 52',city:'Bucuresti',fb_id:'jhon-doe52',email: :fb_id)
User.create(name:'Jhon Doe 53',city:'Bucuresti',fb_id:'jhon-doe53',email: :fb_id)
User.create(name:'Jhon Doe 54',city:'Bucuresti',fb_id:'jhon-doe54',email: :fb_id)
User.create(name:'Jhon Doe 55',city:'Bucuresti',fb_id:'jhon-doe55',email: :fb_id)
User.create(name:'Jhon Doe 56',city:'Bucuresti',fb_id:'jhon-doe56',email: :fb_id)
User.create(name:'Jhon Doe 57',city:'Bucuresti',fb_id:'jhon-doe57',email: :fb_id)
User.create(name:'Jhon Doe 58',city:'Bucuresti',fb_id:'jhon-doe58',email: :fb_id)
User.create(name:'Jhon Doe 59',city:'Bucuresti',fb_id:'jhon-doe59',email: :fb_id)
User.create(name:'Jhon Doe 60',city:'Bucuresti',fb_id:'jhon-doe60',email: :fb_id)



Tournament.create(name:'Football Masters',data: DateTime.new(2012,11,20),sport_id:1)
Tournament.create(name:'Play Day',data:DateTime.new(2012,11,30),sport_id:3)
Tournament.create(name:'The CUP',data: DateTime.new(2012,11,29),sport_id:2)
Tournament.create(name:'Play & Win',data:DateTime.new(2012,12,7),sport_id:4)
Tournament.create(name:'The Football Stars',data:DateTime.new(2012,11,13),sport_id:1)
Tournament.create(name:'Winner`s Race',data:DateTime.new(2012,1,9),sport_id:5)
Tournament.create(name:'Milky Way Stars',data:DateTime.new(2012,9,8),sport_id:6)
Tournament.create(name:'Nike Cup',data:DateTime.new(2012,12,20),sport_id:7)

Team.create(name:'Team1',captain_id:1)
Team.create(name:'Team2',captain_id:2)
Team.create(name:'Team3',captain_id:3)
Team.create(name:'Team4',captain_id:4)
Team.create(name:'Team5',captain_id:5)
Team.create(name:'Team6',captain_id:6)
Team.create(name:'Team7',captain_id:7)
Team.create(name:'Team8',captain_id:8)
Team.create(name:'Team9',captain_id:9)
Team.create(name:'Team10',captain_id:10)
Team.create(name:'Team11',captain_id:11)
Team.create(name:'Team12',captain_id:35)
Team.create(name:'Team13',captain_id:37)
Team.create(name:'Team14',captain_id:38)
Team.create(name:'Team15',captain_id:39)
Team.create(name:'Team16',captain_id:40)
Team.create(name:'Team17',captain_id:41)
Team.create(name:'Team18',captain_id:42)
Team.create(name:'Team19',captain_id:43)
Team.create(name:'Team20',captain_id:44)
Team.create(name:'Team21',captain_id:45)
Team.create(name:'Team22',captain_id:46)
Team.create(name:'Team23',captain_id:47)
Team.create(name:'Team24',captain_id:48)
Team.create(name:'Team25',captain_id:49)
Team.create(name:'Team26',captain_id:50)




Game.create(latitude:"44.437711",longitude:"26.097367",scor_team1:1,scor_team2:0,duration:45,team1_id:1,team2_id:2,state:"on",sport_id:1)
Game.create(latitude:"44.437731",longitude:"26.097357",scor_team1:4,scor_team2:1,duration:5,team1_id:3, team2_id:4, state:"on",sport_id:1)
Game.create(latitude:"44.435311",longitude:"26.097367",scor_team1:4,scor_team2:3,duration:96,team1_id:5, team2_id:6, state:"off",sport_id:1)
Game.create(latitude:"44.432001",longitude:"26.086367",scor_team1:1,scor_team2:2,duration:76,team1_id:7, team2_id:8, state:"on",sport_id:1)
Game.create(latitude:"44.432311",longitude:"26.084367",scor_team1:0,scor_team2:3,duration:81,team1_id:9, team2_id:10, state:"on",sport_id:1)
Game.create(latitude:"44.435011",longitude:"26.107367",scor_team1:8,scor_team2:10,duration:20,team1_id:17, team2_id:18, state:"on",sport_id:2)
Game.create(latitude:"44.433511",longitude:"26.086267",scor_team1:12,scor_team2:18,duration:55,team1_id:19, team2_id:20, state:"on",sport_id:2)
Game.create(latitude:"44.435311",longitude:"26.102328",scor_team1:35,scor_team2:45,duration:45,team1_id:21, team2_id:22, state:"on",sport_id:2)
Game.create(latitude:"44.434511",longitude:"26.102228",scor_team1:20,scor_team2:23,duration:30,team1_id:15, team2_id:16, state:"on",sport_id:2)
Game.create(latitude:"44.435211",longitude:"26.102528",scor_team1:2,scor_team2:2,duration:78,team1_id:25, team2_id:26, state:"on",sport_id:1)





TeamPlayer.create(team_id:1,user_id:1)
TeamPlayer.create(team_id:1,user_id:12)
TeamPlayer.create(team_id:1,user_id:13)
TeamPlayer.create(team_id:1,user_id:14)
TeamPlayer.create(team_id:2,user_id:15)
TeamPlayer.create(team_id:2,user_id:2)
TeamPlayer.create(team_id:2,user_id:16)
TeamPlayer.create(team_id:3,user_id:18)
TeamPlayer.create(team_id:3,user_id:19)
TeamPlayer.create(team_id:3,user_id:20)
TeamPlayer.create(team_id:3,user_id:3)
TeamPlayer.create(team_id:4,user_id:4)
TeamPlayer.create(team_id:4,user_id:21)
TeamPlayer.create(team_id:4,user_id:22)
TeamPlayer.create(team_id:4,user_id:23)
TeamPlayer.create(team_id:5,user_id:24)
TeamPlayer.create(team_id:5,user_id:5)
TeamPlayer.create(team_id:5,user_id:25)
TeamPlayer.create(team_id:6,user_id:6)
TeamPlayer.create(team_id:6,user_id:26)
TeamPlayer.create(team_id:7,user_id:7)
TeamPlayer.create(team_id:7,user_id:27)
TeamPlayer.create(team_id:8,user_id:8)
TeamPlayer.create(team_id:8,user_id:28)
TeamPlayer.create(team_id:9,user_id:9)
TeamPlayer.create(team_id:9,user_id:29)
TeamPlayer.create(team_id:10,user_id:10)
TeamPlayer.create(team_id:10,user_id:30)
TeamPlayer.create(team_id:15,user_id:31)
TeamPlayer.create(team_id:15,user_id:39)
TeamPlayer.create(team_id:16,user_id:32)
TeamPlayer.create(team_id:16,user_id:40)
TeamPlayer.create(team_id:17,user_id:33)
TeamPlayer.create(team_id:17,user_id:41)
TeamPlayer.create(team_id:18,user_id:34)
TeamPlayer.create(team_id:18,user_id:42)
TeamPlayer.create(team_id:19,user_id:51)
TeamPlayer.create(team_id:19,user_id:43)
TeamPlayer.create(team_id:20,user_id:52)
TeamPlayer.create(team_id:20,user_id:44)
TeamPlayer.create(team_id:21,user_id:53)
TeamPlayer.create(team_id:21,user_id:45)
TeamPlayer.create(team_id:22,user_id:54)
TeamPlayer.create(team_id:22,user_id:46)
TeamPlayer.create(team_id:25,user_id:55)
TeamPlayer.create(team_id:25,user_id:49)
TeamPlayer.create(team_id:26,user_id:56)
TeamPlayer.create(team_id:26,user_id:50)



UserGame.create(game_id:1,user_id:1,points:2)
UserGame.create(game_id:1,user_id:2,points:1)
UserGame.create(game_id:2,user_id:3,points:2)
UserGame.create(game_id:2,user_id:4,points:1)
UserGame.create(game_id:3,user_id:5,points:1)
UserGame.create(game_id:3,user_id:6,points:1)
UserGame.create(game_id:4,user_id:7,points:1)
UserGame.create(game_id:4,user_id:8,points:1)
UserGame.create(game_id:5,user_id:9,points:1)
UserGame.create(game_id:5,user_id:10,points:1)
UserGame.create(game_id:1,user_id:12,points:1)
UserGame.create(game_id:1,user_id:13,points:1)
UserGame.create(game_id:1,user_id:14,points:1)
UserGame.create(game_id:1,user_id:15,points:1)
UserGame.create(game_id:1,user_id:16,points:1)
UserGame.create(game_id:2,user_id:18,points:1)
UserGame.create(game_id:2,user_id:19,points:1)
UserGame.create(game_id:2,user_id:20,points:1)
UserGame.create(game_id:2,user_id:21,points:1)
UserGame.create(game_id:2,user_id:22,points:1)
UserGame.create(game_id:2,user_id:23,points:1)
UserGame.create(game_id:3,user_id:24,points:1)
UserGame.create(game_id:3,user_id:25,points:1)
UserGame.create(game_id:3,user_id:26,points:1)
UserGame.create(game_id:4,user_id:27,points:1)
UserGame.create(game_id:4,user_id:28,points:1)
UserGame.create(game_id:5,user_id:29,points:1)
UserGame.create(game_id:5,user_id:30,points:1)
UserGame.create(game_id:9,user_id:31,points:1)
UserGame.create(game_id:9,user_id:32,points:1)
UserGame.create(game_id:6,user_id:33,points:1)
UserGame.create(game_id:6,user_id:34,points:1)
UserGame.create(game_id:9,user_id:39,points:1)
UserGame.create(game_id:9,user_id:40,points:1)
UserGame.create(game_id:6,user_id:41,points:1)
UserGame.create(game_id:6,user_id:42,points:1)
UserGame.create(game_id:7,user_id:43,points:1)
UserGame.create(game_id:7,user_id:44,points:1)
UserGame.create(game_id:8,user_id:45,points:1)
UserGame.create(game_id:8,user_id:46,points:1)
UserGame.create(game_id:10,user_id:49,points:1)
UserGame.create(game_id:10,user_id:50,points:1)
UserGame.create(game_id:7,user_id:51,points:1)
UserGame.create(game_id:7,user_id:52,points:1)
UserGame.create(game_id:8,user_id:53,points:1)
UserGame.create(game_id:8,user_id:54,points:1)
UserGame.create(game_id:10,user_id:55,points:1)
UserGame.create(game_id:10,user_id:56,points:1)


Game.create(latitude:"44.437711",longitude:"26.097367",scor_team1:1,scor_team2:0,duration:45,team1_id:'Team2',team2_id:'Team2',state:"on",sport_id:1)
Game.create(latitude:"44.437711",longitude:"26.097367",scor_team1:1,scor_team2:0,duration:45,team1_id:'Team1',team2_id:'Team2',state:"on",sport_id:1)
Game.create(latitude:"44.437711",longitude:"26.097367",scor_team1:1,scor_team2:0,duration:45,team1_id:'Team5',team2_id:'Team3',state:"on",sport_id:1)

TournamentGame.create(tournament_id:1,game_id:1)
TournamentGame.create(tournament_id:1,game_id:2)
TournamentGame.create(tournament_id:1,game_id:3)
TournamentGame.create(tournament_id:1,game_id:4)

